# Generated by Django 4.2.2 on 2023-09-20 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cohorteDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohorteNumber', models.IntegerField()),
                ('cohorteStatus', models.BooleanField(default=False)),
                ('numberParticipants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dni', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('password', models.CharField(max_length=128)),
                ('employability', models.BooleanField(default=False)),
                ('cohorte', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.cohortedate')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.company')),
            ],
        ),
    ]
