# Generated by Django 4.2.2 on 2023-09-18 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cedula',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
